version: '3.1'

services:

  web:
    container_name: nodejs2023Q2-service-app
    image: thirdmadman/nodejs2023q2-service-app-dev
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
    build: 
      dockerfile: ./.docker/node.dockerfile
      target: install
    command:
      - /bin/sh
      - -c
      - |
        npm run start:dev
    volumes:
      - ./src:/usr/app/src
      - node_modules_dev:/usr/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    restart: always

volumes:
  node_modules_dev:
