apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{.Values.api.replicaCount}}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: {{.Values.api.image}}
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: {{.Values.api.env.PORT}}
          resources:
            requests:
              memory: {{.Values.api.resources.requests.memory}}
              cpu: {{.Values.api.resources.requests.cpu}}
