apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud
spec:
  replicas: {{.Values.crud.replicaCount}}
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      labels:
        app: crud
    spec:
      containers:
        - name: crud
          image: {{.Values.crud.image}}
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "{{.Values.crud.env.API_PORT}}"
          resources:
            requests:
              memory: {{.Values.crud.resources.requests.memory}}
              cpu: {{.Values.crud.resources.requests.cpu}}
